language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t users-api  ./users-api
  - docker tag users-api sahilgarg5794/users-api-udacity:latest
  - docker build -t feed-api ./feed-api
  - docker tag feed-api sahilgarg5794/feed-api-udacity:latest
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend sahilgarg5794/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push YOUR_DOCKER_HUB/simple-node
