# This file is used for convenience of local development.
# DO NOT STORE YOUR CREDENTIALS INTO GIT
POSTGRES_USERNAME=
POSTGRES_PASSWORD=
POSTGRES_DATABASE=
POSTGRES_HOST=
AWS_REGION=
AWS_PROFILE=
AWS_BUCKET=
JWT_SECRET=
URL=
