apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: feed-api
  name: feed-api-service
  selfLink: /api/v1/namespaces/default/services/feed-api-service
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: feed-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
