apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy-dpl
  labels:
    app: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        image: sahilgarg5794/reverse-proxy-udacity
        ports:
        - containerPort: 8080
