apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: reverse-proxy
  name: reverse-proxy-service
  selfLink: /api/v1/namespaces/default/services/reverse-proxy-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: reverse-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
